others:
spring:
  profiles:
    active: data
#  data:
#    students:
#      list:
#        -
#          name: Ravi
#          rollNumber: 10
#        -
#          name: Bhushan
#          rollNumber: 11
management:
  endpoints:
    web:
      exposure:
        include: "*"