spring:
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/r-bhushan/spring-cloud-config
          uri: git@github.com:r-bhushan/spring-cloud-examples.git
          ignoreLocalSshSettings: true
          searchPaths: central-config
          privateKey: |
 server:
  port: 8888
